// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function ChangePIN(arg1:string,arg2:string):Promise<void>;

export function ChangeUserPIN(arg1:number,arg2:string):Promise<void>;

export function CreateCall(arg1:db.Call,arg2:Array<number>,arg3:Array<number>,arg4:Array<string>):Promise<void>;

export function CreatePicklist(arg1:string,arg2:string,arg3:number):Promise<void>;

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<void>;

export function DeleteCall(arg1:number):Promise<void>;

export function DeletePicklist(arg1:number):Promise<void>;

export function DeleteUser(arg1:number):Promise<void>;

export function GetActiveUsers():Promise<Array<db.User>>;

export function GetAdminUsers():Promise<Array<db.User>>;

export function GetAllUsers():Promise<Array<db.User>>;

export function GetCallByID(arg1:number):Promise<db.Call>;

export function GetCallYears():Promise<Array<number>>;

export function GetCallsByYear(arg1:number):Promise<Array<db.Call>>;

export function GetCurrentUser():Promise<db.User>;

export function GetNextCallNumber(arg1:number):Promise<string>;

export function GetPicklistByCategory(arg1:string):Promise<Array<db.Picklist>>;

export function GetRecentCalls(arg1:number):Promise<Array<db.Call>>;

export function GetUserByID(arg1:number):Promise<db.User>;

export function GetVersion():Promise<Record<string, string>>;

export function Login(arg1:string,arg2:string):Promise<db.User>;

export function Logout():Promise<void>;

export function SearchCalls(arg1:string):Promise<Array<db.Call>>;

export function UpdateCall(arg1:db.Call,arg2:Array<number>,arg3:Array<number>,arg4:Array<string>):Promise<void>;

export function UpdatePicklist(arg1:db.Picklist):Promise<void>;

export function UpdateUser(arg1:db.User):Promise<void>;

export function UpdateUserAdminStatus(arg1:number,arg2:boolean):Promise<void>;

export function UpdateUserJoinDate(arg1:number,arg2:string):Promise<void>;

export function UpdateUserPosition(arg1:number,arg2:string):Promise<void>;
