// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePIN(arg1, arg2) {
  return window['go']['main']['App']['ChangePIN'](arg1, arg2);
}

export function ChangeUserPIN(arg1, arg2) {
  return window['go']['main']['App']['ChangeUserPIN'](arg1, arg2);
}

export function CreateCall(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateCall'](arg1, arg2, arg3, arg4);
}

export function CreatePicklist(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePicklist'](arg1, arg2, arg3);
}

export function CreateUser(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteCall(arg1) {
  return window['go']['main']['App']['DeleteCall'](arg1);
}

export function DeletePicklist(arg1) {
  return window['go']['main']['App']['DeletePicklist'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function GetActiveUsers() {
  return window['go']['main']['App']['GetActiveUsers']();
}

export function GetAdminUsers() {
  return window['go']['main']['App']['GetAdminUsers']();
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetCallByID(arg1) {
  return window['go']['main']['App']['GetCallByID'](arg1);
}

export function GetCallYears() {
  return window['go']['main']['App']['GetCallYears']();
}

export function GetCallsByYear(arg1) {
  return window['go']['main']['App']['GetCallsByYear'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetNextCallNumber(arg1) {
  return window['go']['main']['App']['GetNextCallNumber'](arg1);
}

export function GetPicklistByCategory(arg1) {
  return window['go']['main']['App']['GetPicklistByCategory'](arg1);
}

export function GetRecentCalls(arg1) {
  return window['go']['main']['App']['GetRecentCalls'](arg1);
}

export function GetUserByID(arg1) {
  return window['go']['main']['App']['GetUserByID'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function SearchCalls(arg1) {
  return window['go']['main']['App']['SearchCalls'](arg1);
}

export function UpdateCall(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateCall'](arg1, arg2, arg3, arg4);
}

export function UpdatePicklist(arg1) {
  return window['go']['main']['App']['UpdatePicklist'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['main']['App']['UpdateUser'](arg1);
}

export function UpdateUserAdminStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserAdminStatus'](arg1, arg2);
}

export function UpdateUserJoinDate(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserJoinDate'](arg1, arg2);
}

export function UpdateUserPosition(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserPosition'](arg1, arg2);
}
